from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor


def generate_document_id() -> str:
    return f"MOM-{datetime.now().strftime('%Y%m%d')}-001"


def set_cell_text(
    cell,
    text: str,
    bold: bool = False,
    font_size: int = 10
):
    cell.text = ""

    paragraph = cell.paragraphs[0]
    paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT

    run = paragraph.add_run(text)
    run.bold = bold
    run.font.size = Pt(font_size)
    run.font.name = "Times New Roman"

    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.TOP


def shade_cell(cell, fill: str):
    tc_pr = cell._tc.get_or_add_tcPr()
    shading = tc_pr.xpath("w:shd")

    if shading:
        shading[0].set(
            "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}fill",
            fill
        )
    else:
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn

        shd = OxmlElement("w:shd")
        shd.set(qn("w:fill"), fill)
        tc_pr.append(shd)


def add_footer(doc: Document):
    document_id = generate_document_id()
    generated_date = datetime.now().strftime("%B %d, %Y %I:%M %p")

    footer = doc.sections[0].footer
    paragraph = footer.paragraphs[0]
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = paragraph.add_run(
        "Generated by AI Meeting Notes Summarizer\n"
        f"Generated Date: {generated_date}\n"
        f"Document ID: {document_id}"
    )

    run.font.size = Pt(8)
    run.font.name = "Times New Roman"


def generate_docx(
    company_name: str,
    subject: str,
    date: str,
    time: str,
    attendees: str,
    agenda: str,
    summary: str,
    decisions_made: str,
    tasks: str,
    owners: str,
    blockers: str,
    followups: str,
    meeting_outcome: str
) -> str:
    output_dir = Path("agent_1_sum/output/docx")
    output_dir.mkdir(parents=True, exist_ok=True)

    file_name = f"Meeting_Notes_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    docx_path = output_dir / file_name

    doc = Document()

    section = doc.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

    header_table = doc.add_table(rows=1, cols=2)
    header_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    header_table.autofit = True

    logo_cell = header_table.cell(0, 0)
    info_cell = header_table.cell(0, 1)

    logo_paragraph = logo_cell.paragraphs[0]
    logo_paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT

    logo_path = Path(
    "agent_1_sum/output/assets/direc_logo.png"
        )

    if logo_path.exists():
        logo_run = logo_paragraph.add_run()
        logo_run.add_picture(str(logo_path), width=Inches(1.2))
    else:
        logo_run = logo_paragraph.add_run("direc")
        logo_run.bold = True
        logo_run.font.size = Pt(22)

    info_paragraph = info_cell.paragraphs[0]
    info_paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    info_run = info_paragraph.add_run(
        "4F, Victoria One Bldg. 1670 Quezon Ave.\n"
        "South Triangle, Quezon City, Philippines\n"
        "www.direcbusiness.com\n"
        "(02) 8555 1547"
    )
    info_run.font.size = Pt(8)
    info_run.font.name = "Times New Roman"

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    title_run = title.add_run("Minutes of Meeting")
    title_run.bold = True
    title_run.font.size = Pt(14)
    title_run.font.name = "Times New Roman"

    info_table = doc.add_table(rows=4, cols=4)
    info_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    info_table.style = "Table Grid"

    set_cell_text(info_table.cell(0, 0), "Company Name", bold=True)
    set_cell_text(info_table.cell(0, 1), company_name)
    info_table.cell(0, 1).merge(info_table.cell(0, 3))

    set_cell_text(info_table.cell(1, 0), "Subject", bold=True)
    set_cell_text(info_table.cell(1, 1), subject)
    info_table.cell(1, 1).merge(info_table.cell(1, 3))

    set_cell_text(info_table.cell(2, 0), "Date", bold=True)
    set_cell_text(info_table.cell(2, 1), date)
    set_cell_text(info_table.cell(2, 2), "Meeting Attendees", bold=True)
    set_cell_text(info_table.cell(2, 3), attendees)

    set_cell_text(info_table.cell(3, 0), "Time", bold=True)
    set_cell_text(info_table.cell(3, 1), time)
    set_cell_text(info_table.cell(3, 2), "Agenda / Objective", bold=True)
    set_cell_text(info_table.cell(3, 3), agenda)

    doc.add_paragraph("")

    mom_table = doc.add_table(rows=1, cols=4)
    mom_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    mom_table.style = "Table Grid"

    headers = [
        "ITEM",
        "ACTION",
        "STATUS",
        "PIC & TARGET DATE"
    ]

    for index, header in enumerate(headers):
        cell = mom_table.rows[0].cells[index]
        set_cell_text(cell, header, bold=True)
        shade_cell(cell, "D9F2D0")

    rows = [
        (
            "Discussion Points",
            summary,
            "Generated",
            "AI Generated"
        ),
        (
            "Decisions Made",
            decisions_made,
            "For Review",
            "Concerned PIC"
        ),
        (
            "Action Items",
            tasks,
            "Open",
            "To be assigned"
        ),
        (
            "Owners",
            owners,
            "For Review",
            "Concerned PIC"
        ),
        (
            "Risks / Issues / Blockers",
            blockers,
            "Pending",
            "Concerned Team"
        ),
        (
            "Follow-ups",
            followups,
            "Pending",
            "Next Meeting"
        ),
        (
            "Meeting Outcome",
            meeting_outcome,
            "Generated",
            "AI Generated"
        ),
    ]

    for item, action, status, pic in rows:
        cells = mom_table.add_row().cells

        set_cell_text(cells[0], item, bold=True)
        set_cell_text(cells[1], action)
        set_cell_text(cells[2], status)
        set_cell_text(cells[3], pic)

    add_footer(doc)

    doc.save(docx_path)

    return str(docx_path)